// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owbdprrjmzwqajhyynrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93YmRwcnJqbXp3cWFqaHl5bnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDEwMDUsImV4cCI6MjA3NDAxNzAwNX0.tYxf4y1Ml2Xe1-7d_JP3gyM9YjIP-T3i21wWhdguaHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});